KPMP-4617_add-release
KPMP/hubble-data pull request #18
Opened 2023-08-31 17:46 UTC by Dert1129

2023-08-31 19:10 UTC, rlreamy requested changes
See comments, also you have merge conflicts to deal with

2023-08-31 19:10 UTC, rlreamy commented on src/main/resources/knowledge_environment.graphqls
> +    releaseVersion: Float
Shouldn't this be a String?

2023-08-31 19:10 UTC, rlreamy commented on src/main/java/org/kpmp/spatialViewerDataset/SpatialViewerDatasetService.java
> +                spatialViewerFileDataset.setReleaseVersionDisplay("Recently Released");
This should be extracted to a constant. Remember constants should be `private static final`, and live at the top of the file with other class variables.

2023-08-31 19:10 UTC, rlreamy commented on src/main/java/org/kpmp/spatialViewerDataset/SpatialViewerDatasetService.java
> +    public SpatialViewerDatasetService() {
Spring should have nothing to complain about. You should be able to have an overridden constructor with parameters without defining a default constructor.

2023-09-01 18:15 UTC, zwright commented on src/main/java/org/kpmp/spatialViewerDataset/SpatialViewerDatasetService.java
> +    private static int EQUALITY_OPERATOR = 0;
This is meant to be a constant? You need the "final" keyword too.

2023-09-05 19:32 UTC, zwright approved these changes

2023-09-05 19:33 UTC, merged